<?php

namespace Database\Seeders;

use App\Models\SkuGroup;
use Illuminate\Database\Seeder;

class SkuGroupSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$skuGroups = [
			'Downy Base 720',
			'Downy Base Plus 680',
			'Downy Senso 680',
			'-',
			'-',
			'-',
			'-',
			'Downy Senso 550',
			'Downy Senso 680',
			'Downy Base 1000',
			'Downy Senso 900',
			'-',
			'Downy Base 1500',
			'Downy Base Plus 1450',
			'-',
			'Downy Senso 1450',
			'-',
			'Downy Kenzo 550',
			'Downy Kenzo 900',
			'Downy Kenzo 1450',
			'PTN 160',
			'PTN 130',
			'PTN 290',
			'-',
			'PTN 400',
			'PTN 750',
			'PTN NRC 40',
			'HS 135',
			'HS 160',
			'HS 135',
			'HS 300',
			'HS 400',
			'HS 680',
			'RJC 150',
			'-',
			'RJC 340',
			'-',
			'RJC 450',
			'RJC 600',
			'HE 400',
			'HE 300',
			'Miracle Hair Mask 20ml',
			'Miracle Hair Supplement 70Ml',
			'Miracle Hair Supplement 150ML',
			'Miracle Hair Supplement 300ML',
			'Micellar 300ml',
			'Micellar 530 ML',
			'Blue 2 10S',
			'Flexi 2 2s',
			'Blue 3 2S',
			'Blue 3 4s',
			'Daisy 5s',
			'Venus 4s',
			'Venus Hybrid',
			'Venus Comfortd',
			'Vector Razor',
			'Foam 50g',
			'Mach 3 Razor',
			'Buy Foam + Razor get additional discount',
			'Blue 2 2s',
			'Flexi 2 5+2S',
			'Simply Venus 3 2s',
			'Simply Venus 3 1s',
			'Venus Sensitive ',
			'Venus Smooth',
			'Guard 3 1s/2s',
			'Fusion Razor',
			'Foamy 175g',
			'Flexi 2 3+1s ',
			'Daisy 2s',
			'Gel 200ml/195g',
			'Mach 3 Turbo Razor ',
			'Flexi Vibe',
			'Flexi 3 2s',
			'Olay minis TE Normal cream UV',
			'Olay minis Whip WR 10G',
			'Olay minis Whip RG 10G',
			'Olay RG Day/ Night 10G',
			'Luminous AHA Cream 50gr, AHA serum 30ml',
			'Luminous Vit C Cream 50gr, Serum 30ml',
			'WR Night & day 50G',
			'Luminious Hya Serum & Cica serum 30ml',
			'Olay RG Micro sculpting Day 50G',
			'Olay RG Micro sculpting Night 50G',
			'Olay RG Micro sculpting Serum 50ML',
			'Whips RG Non UV and UV 50G',
			'Whips TE Non UV and UV 50G',
			'Whips WR Non UV and UV 50G',
			'TE Normal SPF 50G',
			'TE Normal 50G',
			'TE Night 50G',
			'Retinol 24 Night Cream 50G',
			'Retinol 24 Night Serum 50G',
			'Retinol 24 Night Eye 15G',
			'Ambi Pur Sky/ Lavender 2ml',
			'Ambi Pur Pacific/Aqua Starter 7.5ml',
			'Vicks Inhaler',
			'Vicks Inhaler Twin',
			'Vicks Vaporub 10',
			'Vicks Vaporub 25',
			'Vicks Vaporub 50',
			'Vicks Jamu 56ml',
			'Vicks Jamu 105ml',
			'Pampers Value Pack',
			'Pampers Super Jumbo Pack',
			'OB AR 123 1s',
			'OB AR 123 2s',
			'OB AR 123 3s',
			'OB AR HERBAL 1s',
			'OB AR HERBAL 3s',
			'OB AR MICROTHIN 1s',
			'OB AR MICROTHIN 3s',
			'OB BLACKTEA 1s',
			'OB BLACKTEA 3s',
			'OB charcoal 1s',
			'OB charcoal 3s',
			'OB FLOSS 50',
			'OB GREENTEA 1s',
			'OB GREENTEA 3s',
			'OB GUM PROTECT 3s',
			'OB KIDS',
			'OB PASTE',
			'OB PROHEALTH 2s',
			'OB PROHEALTH CLINICAL 2s',
			'OB PROHEALTH CLINICAL 3s',
			'OB STAGES',
			'OB WHITE 1s',
			'OB WHITE 2s',
			'TE UV 50G',
			'GIL PIVOT',
		];

		$skuGroups = collect($skuGroups)->map(function ($group) {
			return [
				'name' => $group,
				'created_at' => now(),
				'updated_at' => now(),
			];
		})->all();

		SkuGroup::insert($skuGroups);
	}
}
