<?php

namespace App\Enums;

class TdsEnum
{
	const HOLIDAY = 'HOLIDAY';
	const INCENTIVE = 'INCENTIVE';
	const INVENTORY = 'INVENTORY';
	const INVOICE = 'INVOICE';
	const MASTER_BRANCH = 'MASTER BRANCH';
	const MASTER_CHANNEL = 'MASTER CHANNEL';
	const MASTER_PRICE = 'MASTER PRICE';
	const MASTER_PRODUCT = 'MASTER PRODUCT';
	const MASTER_REASON = 'MASTER REASON';
	const MASTER_STORE = 'MASTER STORE';
	const MASTER_SELLER = 'MASTER SELLER';
	const OVERDUE = 'OVERDUE';
	const PE_SURVEY = 'PE SURVEY';
	const PRODUCT_BUNDLE = 'PRODUCT BUNDLE';
	const PRODUCT_PRIORITY = 'PRODUCT PRIORITY';
	const PROMOTION = 'PROMOTION';
	const PROMOTION_PRICE = 'PROMOTION PRICE';
	const RETURN = 'RETURN';
	const ROUTE_PLAN_DETAIL = 'ROUTE PLAN DETAIL';
	const WEEK_MAPPING = 'WEEK MAPPING';
	const SBD = 'SBD';
	const SBD_MERC = 'SBD MERC';
	const SELLER_TARGET = 'SELLER TARGET';
	const STORE_TARGET = 'STORE TARGET';
	const STORE_PROGRAM = 'STORE PROGRAM';
	const VOUCHER = 'VOUCHER';
}
